# Generated by Django 2.1.5 on 2019-04-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_auto_20190430_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.CharField(default=1, max_length=100, verbose_name='摘要'),
            preserve_default=False,
        ),
    ]
